version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: streetform-app
        container_name: streetform-app
        ports:
            - "8000:9000" # Map host port 8000 to PHP-FPM
        depends_on:
            - mysql
        environment:
            APP_ENV: local
            APP_KEY: base64:zKhRGcEST6M3MNnMid9b1RHJEuYgVaDCwPMV+7TouxQ=
            APP_DEBUG: true
            APP_URL: http://localhost:8000
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: streetform-laravel
            DB_USERNAME: root
            DB_PASSWORD: secret
        volumes:
            - .:/var/www/html
        networks:
            - streetform-network

    mysql:
        image: mysql:8.0
        container_name: streetform-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: streetform-laravel
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - streetform-network

networks:
    streetform-network:

volumes:
    mysql-data:
