version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: streetform-app
        container_name: streetform-app
        ports:
            - "8000:8080"
        depends_on:
            - mysql
            - postgres
        environment:
            APP_ENV: local
            APP_KEY: base64:zKhRGcEST6M3MNnMid9b1RHJEuYgVaDCwPMV+7TouxQ=
            APP_DEBUG: true
            APP_URL: http://localhost:8000
            # Use MySQL locally (change to pgsql to test PostgreSQL)
            DB_CONNECTION: mysql
            DB_HOST: mysql
            DB_PORT: 3306
            DB_DATABASE: streetform-laravel
            DB_USERNAME: root
            DB_PASSWORD: secret
        # volumes:
        #     - .:/var/www/html
        networks:
            - streetform-network

    mysql:
        image: mysql:8.0
        container_name: streetform-mysql
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: streetform-laravel
        ports:
            - "3306:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - streetform-network

    postgres:
        image: postgres:15
        container_name: streetform-postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: streetform_laravel
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        networks:
            - streetform-network

networks:
    streetform-network:

volumes:
    mysql-data:
    postgres-data:
